### Sign up

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123"
}


### Sign in

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123"
}


### Get information

GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDMyMzEyNCwiZXhwIjoxNjg0MzIzMTg0fQ.9yLNOG_HdmMJD7y56u3nPl-9Ut0d6EifI8d_42ciKY8
