### Sign up

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "huy@gmail.com",
  "password": "123"
}


### Sign in

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "huy@gmail.com",
  "password": "123"
}


### Get information

GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaHV5QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg0MjQ3Nzg4LCJleHAiOjE2ODQyNDc4NDh9.CIvKIH0qP3-Q-iiekUCl8rvpFqFl_4a6WaQBthupvF8
